/*
	Generated by KBEngine!
	Please do not modify this file!
	
	tools = kbcmd
*/

namespace KBEngine
{
	using UnityEngine;
	using System;
	using System.Collections;
	using System.Collections.Generic;

	// defined in */scripts/entity_defs/Avatar.def
	public class EntityBaseEntityCall_AvatarBase : EntityCall
	{
		public EntityBaseEntityCall_FrameSyncReportBase componentFrameSync = null;

		public EntityBaseEntityCall_AvatarBase(Int32 eid, string ename) : base(eid, ename)
		{
			componentFrameSync = new EntityBaseEntityCall_FrameSyncReportBase(17, id);
			type = ENTITYCALL_TYPE.ENTITYCALL_TYPE_BASE;
		}

		public void leaveGame()
		{
			Bundle pBundle = newCall("leaveGame", 0);
			if(pBundle == null)
				return;

			sendCall(null);
		}

		public void reqExitMatch()
		{
			Bundle pBundle = newCall("reqExitMatch", 0);
			if(pBundle == null)
				return;

			sendCall(null);
		}

		public void reqHeroInfosByHeroId(Int32 arg1)
		{
			Bundle pBundle = newCall("reqHeroInfosByHeroId", 0);
			if(pBundle == null)
				return;

			bundle.writeInt32(arg1);
			sendCall(null);
		}

		public void reqSkillLst()
		{
			Bundle pBundle = newCall("reqSkillLst", 0);
			if(pBundle == null)
				return;

			sendCall(null);
		}

		public void startGame()
		{
			Bundle pBundle = newCall("startGame", 0);
			if(pBundle == null)
				return;

			sendCall(null);
		}

	}

	public class EntityCellEntityCall_AvatarBase : EntityCall
	{
		public EntityCellEntityCall_FrameSyncReportBase componentFrameSync = null;

		public EntityCellEntityCall_AvatarBase(Int32 eid, string ename) : base(eid, ename)
		{
			componentFrameSync = new EntityCellEntityCall_FrameSyncReportBase(17, id);
			type = ENTITYCALL_TYPE.ENTITYCALL_TYPE_CELL;
		}

		public void submitStatisticalResult(Int32 arg1)
		{
			Bundle pBundle = newCall("submitStatisticalResult", 0);
			if(pBundle == null)
				return;

			bundle.writeInt32(arg1);
			sendCall(null);
		}

	}
	}
