/*
	Generated by KBEngine!
	Please do not modify this file!
	tools = kbcmd
*/

namespace KBEngine
{
	using UnityEngine;
	using System;
	using System.Collections;
	using System.Collections.Generic;

	public class EntityDef
	{
		public static Dictionary<string, UInt16> datatype2id = new Dictionary<string, UInt16>();
		public static Dictionary<string, DATATYPE_BASE> datatypes = new Dictionary<string, DATATYPE_BASE>();
		public static Dictionary<UInt16, DATATYPE_BASE> id2datatypes = new Dictionary<UInt16, DATATYPE_BASE>();
		public static Dictionary<string, Int32> entityclass = new Dictionary<string, Int32>();
		public static Dictionary<string, ScriptModule> moduledefs = new Dictionary<string, ScriptModule>();
		public static Dictionary<UInt16, ScriptModule> idmoduledefs = new Dictionary<UInt16, ScriptModule>();

		public static bool init()
		{
			initDataTypes();
			initDefTypes();
			initScriptModules();
			return true;
		}

		public static bool reset()
		{
			clear();
			return init();
		}

		public static void clear()
		{
			datatype2id.Clear();
			datatypes.Clear();
			id2datatypes.Clear();
			entityclass.Clear();
			moduledefs.Clear();
			idmoduledefs.Clear();
		}

		public static void initDataTypes()
		{
			datatypes["UINT8"] = new DATATYPE_UINT8();
			datatypes["UINT16"] = new DATATYPE_UINT16();
			datatypes["UINT32"] = new DATATYPE_UINT32();
			datatypes["UINT64"] = new DATATYPE_UINT64();

			datatypes["INT8"] = new DATATYPE_INT8();
			datatypes["INT16"] = new DATATYPE_INT16();
			datatypes["INT32"] = new DATATYPE_INT32();
			datatypes["INT64"] = new DATATYPE_INT64();

			datatypes["FLOAT"] = new DATATYPE_FLOAT();
			datatypes["DOUBLE"] = new DATATYPE_DOUBLE();

			datatypes["STRING"] = new DATATYPE_STRING();
			datatypes["VECTOR2"] = new DATATYPE_VECTOR2();

			datatypes["VECTOR3"] = new DATATYPE_VECTOR3();

			datatypes["VECTOR4"] = new DATATYPE_VECTOR4();
			datatypes["PYTHON"] = new DATATYPE_PYTHON();

			datatypes["UNICODE"] = new DATATYPE_UNICODE();
			datatypes["ENTITYCALL"] = new DATATYPE_ENTITYCALL();

			datatypes["BLOB"] = new DATATYPE_BLOB();
		}

		public static void initScriptModules()
		{
			ScriptModule pAvatarModule = new ScriptModule("Avatar");
			EntityDef.moduledefs["Avatar"] = pAvatarModule;
			EntityDef.idmoduledefs[1] = pAvatarModule;

			Property pAvatar_position = new Property();
			pAvatar_position.name = "position";
			pAvatar_position.properUtype = 40000;
			pAvatar_position.properFlags = 4;
			pAvatar_position.aliasID = 1;
			Vector3 Avatar_position_defval = new Vector3();
			pAvatar_position.defaultVal = Avatar_position_defval;
			pAvatarModule.propertys["position"] = pAvatar_position; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_position.aliasID] = pAvatar_position;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(position / 40000).");

			Property pAvatar_direction = new Property();
			pAvatar_direction.name = "direction";
			pAvatar_direction.properUtype = 40001;
			pAvatar_direction.properFlags = 4;
			pAvatar_direction.aliasID = 2;
			Vector3 Avatar_direction_defval = new Vector3();
			pAvatar_direction.defaultVal = Avatar_direction_defval;
			pAvatarModule.propertys["direction"] = pAvatar_direction; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_direction.aliasID] = pAvatar_direction;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(direction / 40001).");

			Property pAvatar_spaceID = new Property();
			pAvatar_spaceID.name = "spaceID";
			pAvatar_spaceID.properUtype = 40002;
			pAvatar_spaceID.properFlags = 16;
			pAvatar_spaceID.aliasID = 3;
			UInt32 Avatar_spaceID_defval;
			UInt32.TryParse("", out Avatar_spaceID_defval);
			pAvatar_spaceID.defaultVal = Avatar_spaceID_defval;
			pAvatarModule.propertys["spaceID"] = pAvatar_spaceID; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_spaceID.aliasID] = pAvatar_spaceID;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(spaceID / 40002).");

			Property pAvatar_componentFrameSync = new Property();
			pAvatar_componentFrameSync.name = "componentFrameSync";
			pAvatar_componentFrameSync.properUtype = 17;
			pAvatar_componentFrameSync.properFlags = 157;
			pAvatar_componentFrameSync.aliasID = 4;
			pAvatarModule.propertys["componentFrameSync"] = pAvatar_componentFrameSync; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_componentFrameSync.aliasID] = pAvatar_componentFrameSync;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(componentFrameSync / 17).");

			Property pAvatar_gameStateC = new Property();
			pAvatar_gameStateC.name = "gameStateC";
			pAvatar_gameStateC.properUtype = 13;
			pAvatar_gameStateC.properFlags = 4;
			pAvatar_gameStateC.aliasID = 5;
			SByte Avatar_gameStateC_defval;
			SByte.TryParse("", out Avatar_gameStateC_defval);
			pAvatar_gameStateC.defaultVal = Avatar_gameStateC_defval;
			pAvatarModule.propertys["gameStateC"] = pAvatar_gameStateC; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_gameStateC.aliasID] = pAvatar_gameStateC;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(gameStateC / 13).");

			Property pAvatar_heroId = new Property();
			pAvatar_heroId.name = "heroId";
			pAvatar_heroId.properUtype = 5;
			pAvatar_heroId.properFlags = 4;
			pAvatar_heroId.aliasID = 6;
			Int32 Avatar_heroId_defval;
			Int32.TryParse("0", out Avatar_heroId_defval);
			pAvatar_heroId.defaultVal = Avatar_heroId_defval;
			pAvatarModule.propertys["heroId"] = pAvatar_heroId; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_heroId.aliasID] = pAvatar_heroId;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(heroId / 5).");

			Property pAvatar_level = new Property();
			pAvatar_level.name = "level";
			pAvatar_level.properUtype = 15;
			pAvatar_level.properFlags = 4;
			pAvatar_level.aliasID = 7;
			SByte Avatar_level_defval;
			SByte.TryParse("", out Avatar_level_defval);
			pAvatar_level.defaultVal = Avatar_level_defval;
			pAvatarModule.propertys["level"] = pAvatar_level; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_level.aliasID] = pAvatar_level;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(level / 15).");

			Property pAvatar_name = new Property();
			pAvatar_name.name = "name";
			pAvatar_name.properUtype = 3;
			pAvatar_name.properFlags = 4;
			pAvatar_name.aliasID = 8;
			string Avatar_name_defval = "";
			pAvatar_name.defaultVal = Avatar_name_defval;
			pAvatarModule.propertys["name"] = pAvatar_name; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_name.aliasID] = pAvatar_name;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(name / 3).");

			Property pAvatar_roundCount = new Property();
			pAvatar_roundCount.name = "roundCount";
			pAvatar_roundCount.properUtype = 12;
			pAvatar_roundCount.properFlags = 4;
			pAvatar_roundCount.aliasID = 9;
			SByte Avatar_roundCount_defval;
			SByte.TryParse("", out Avatar_roundCount_defval);
			pAvatar_roundCount.defaultVal = Avatar_roundCount_defval;
			pAvatarModule.propertys["roundCount"] = pAvatar_roundCount; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_roundCount.aliasID] = pAvatar_roundCount;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(roundCount / 12).");

			Property pAvatar_seatNo = new Property();
			pAvatar_seatNo.name = "seatNo";
			pAvatar_seatNo.properUtype = 14;
			pAvatar_seatNo.properFlags = 4;
			pAvatar_seatNo.aliasID = 10;
			SByte Avatar_seatNo_defval;
			SByte.TryParse("", out Avatar_seatNo_defval);
			pAvatar_seatNo.defaultVal = Avatar_seatNo_defval;
			pAvatarModule.propertys["seatNo"] = pAvatar_seatNo; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_seatNo.aliasID] = pAvatar_seatNo;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(seatNo / 14).");

			Property pAvatar_teamId = new Property();
			pAvatar_teamId.name = "teamId";
			pAvatar_teamId.properUtype = 9;
			pAvatar_teamId.properFlags = 4;
			pAvatar_teamId.aliasID = 11;
			Int32 Avatar_teamId_defval;
			Int32.TryParse("", out Avatar_teamId_defval);
			pAvatar_teamId.defaultVal = Avatar_teamId_defval;
			pAvatarModule.propertys["teamId"] = pAvatar_teamId; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_teamId.aliasID] = pAvatar_teamId;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(teamId / 9).");

			Property pAvatar_winRate = new Property();
			pAvatar_winRate.name = "winRate";
			pAvatar_winRate.properUtype = 11;
			pAvatar_winRate.properFlags = 4;
			pAvatar_winRate.aliasID = 12;
			SByte Avatar_winRate_defval;
			SByte.TryParse("", out Avatar_winRate_defval);
			pAvatar_winRate.defaultVal = Avatar_winRate_defval;
			pAvatarModule.propertys["winRate"] = pAvatar_winRate; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_winRate.aliasID] = pAvatar_winRate;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(winRate / 11).");

			List<DATATYPE_BASE> pAvatar_onExitMatch_args = new List<DATATYPE_BASE>();
			pAvatar_onExitMatch_args.Add(EntityDef.id2datatypes[8]);

			Method pAvatar_onExitMatch = new Method();
			pAvatar_onExitMatch.name = "onExitMatch";
			pAvatar_onExitMatch.methodUtype = 18;
			pAvatar_onExitMatch.aliasID = 1;
			pAvatar_onExitMatch.args = pAvatar_onExitMatch_args;

			pAvatarModule.methods["onExitMatch"] = pAvatar_onExitMatch; 
			pAvatarModule.useMethodDescrAlias = true;
			pAvatarModule.idmethods[(UInt16)pAvatar_onExitMatch.aliasID] = pAvatar_onExitMatch;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(onExitMatch / 18).");

			List<DATATYPE_BASE> pAvatar_onHeroIdChanged_args = new List<DATATYPE_BASE>();
			pAvatar_onHeroIdChanged_args.Add(EntityDef.id2datatypes[8]);
			pAvatar_onHeroIdChanged_args.Add(EntityDef.id2datatypes[8]);

			Method pAvatar_onHeroIdChanged = new Method();
			pAvatar_onHeroIdChanged.name = "onHeroIdChanged";
			pAvatar_onHeroIdChanged.methodUtype = 15;
			pAvatar_onHeroIdChanged.aliasID = 2;
			pAvatar_onHeroIdChanged.args = pAvatar_onHeroIdChanged_args;

			pAvatarModule.methods["onHeroIdChanged"] = pAvatar_onHeroIdChanged; 
			pAvatarModule.useMethodDescrAlias = true;
			pAvatarModule.idmethods[(UInt16)pAvatar_onHeroIdChanged.aliasID] = pAvatar_onHeroIdChanged;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(onHeroIdChanged / 15).");

			List<DATATYPE_BASE> pAvatar_onLoadingToReadyBattleState_args = new List<DATATYPE_BASE>();

			Method pAvatar_onLoadingToReadyBattleState = new Method();
			pAvatar_onLoadingToReadyBattleState.name = "onLoadingToReadyBattleState";
			pAvatar_onLoadingToReadyBattleState.methodUtype = 16;
			pAvatar_onLoadingToReadyBattleState.aliasID = 3;
			pAvatar_onLoadingToReadyBattleState.args = pAvatar_onLoadingToReadyBattleState_args;

			pAvatarModule.methods["onLoadingToReadyBattleState"] = pAvatar_onLoadingToReadyBattleState; 
			pAvatarModule.useMethodDescrAlias = true;
			pAvatarModule.idmethods[(UInt16)pAvatar_onLoadingToReadyBattleState.aliasID] = pAvatar_onLoadingToReadyBattleState;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(onLoadingToReadyBattleState / 16).");

			List<DATATYPE_BASE> pAvatar_onPushAvatarCurrentScene_args = new List<DATATYPE_BASE>();
			pAvatar_onPushAvatarCurrentScene_args.Add(EntityDef.id2datatypes[4]);

			Method pAvatar_onPushAvatarCurrentScene = new Method();
			pAvatar_onPushAvatarCurrentScene.name = "onPushAvatarCurrentScene";
			pAvatar_onPushAvatarCurrentScene.methodUtype = 13;
			pAvatar_onPushAvatarCurrentScene.aliasID = 4;
			pAvatar_onPushAvatarCurrentScene.args = pAvatar_onPushAvatarCurrentScene_args;

			pAvatarModule.methods["onPushAvatarCurrentScene"] = pAvatar_onPushAvatarCurrentScene; 
			pAvatarModule.useMethodDescrAlias = true;
			pAvatarModule.idmethods[(UInt16)pAvatar_onPushAvatarCurrentScene.aliasID] = pAvatar_onPushAvatarCurrentScene;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(onPushAvatarCurrentScene / 13).");

			List<DATATYPE_BASE> pAvatar_onPushMatchPlayersData_args = new List<DATATYPE_BASE>();
			pAvatar_onPushMatchPlayersData_args.Add(EntityDef.id2datatypes[35]);

			Method pAvatar_onPushMatchPlayersData = new Method();
			pAvatar_onPushMatchPlayersData.name = "onPushMatchPlayersData";
			pAvatar_onPushMatchPlayersData.methodUtype = 14;
			pAvatar_onPushMatchPlayersData.aliasID = 5;
			pAvatar_onPushMatchPlayersData.args = pAvatar_onPushMatchPlayersData_args;

			pAvatarModule.methods["onPushMatchPlayersData"] = pAvatar_onPushMatchPlayersData; 
			pAvatarModule.useMethodDescrAlias = true;
			pAvatarModule.idmethods[(UInt16)pAvatar_onPushMatchPlayersData.aliasID] = pAvatar_onPushMatchPlayersData;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(onPushMatchPlayersData / 14).");

			List<DATATYPE_BASE> pAvatar_onPushStatisticalResult_args = new List<DATATYPE_BASE>();
			pAvatar_onPushStatisticalResult_args.Add(EntityDef.id2datatypes[8]);

			Method pAvatar_onPushStatisticalResult = new Method();
			pAvatar_onPushStatisticalResult.name = "onPushStatisticalResult";
			pAvatar_onPushStatisticalResult.methodUtype = 12;
			pAvatar_onPushStatisticalResult.aliasID = 6;
			pAvatar_onPushStatisticalResult.args = pAvatar_onPushStatisticalResult_args;

			pAvatarModule.methods["onPushStatisticalResult"] = pAvatar_onPushStatisticalResult; 
			pAvatarModule.useMethodDescrAlias = true;
			pAvatarModule.idmethods[(UInt16)pAvatar_onPushStatisticalResult.aliasID] = pAvatar_onPushStatisticalResult;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(onPushStatisticalResult / 12).");

			List<DATATYPE_BASE> pAvatar_onReadyBattle_args = new List<DATATYPE_BASE>();

			Method pAvatar_onReadyBattle = new Method();
			pAvatar_onReadyBattle.name = "onReadyBattle";
			pAvatar_onReadyBattle.methodUtype = 17;
			pAvatar_onReadyBattle.aliasID = 7;
			pAvatar_onReadyBattle.args = pAvatar_onReadyBattle_args;

			pAvatarModule.methods["onReadyBattle"] = pAvatar_onReadyBattle; 
			pAvatarModule.useMethodDescrAlias = true;
			pAvatarModule.idmethods[(UInt16)pAvatar_onReadyBattle.aliasID] = pAvatar_onReadyBattle;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(onReadyBattle / 17).");

			List<DATATYPE_BASE> pAvatar_onReqsChooseHeroResult_args = new List<DATATYPE_BASE>();
			pAvatar_onReqsChooseHeroResult_args.Add(EntityDef.id2datatypes[23]);
			pAvatar_onReqsChooseHeroResult_args.Add(EntityDef.id2datatypes[25]);

			Method pAvatar_onReqsChooseHeroResult = new Method();
			pAvatar_onReqsChooseHeroResult.name = "onReqsChooseHeroResult";
			pAvatar_onReqsChooseHeroResult.methodUtype = 10;
			pAvatar_onReqsChooseHeroResult.aliasID = 8;
			pAvatar_onReqsChooseHeroResult.args = pAvatar_onReqsChooseHeroResult_args;

			pAvatarModule.methods["onReqsChooseHeroResult"] = pAvatar_onReqsChooseHeroResult; 
			pAvatarModule.useMethodDescrAlias = true;
			pAvatarModule.idmethods[(UInt16)pAvatar_onReqsChooseHeroResult.aliasID] = pAvatar_onReqsChooseHeroResult;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(onReqsChooseHeroResult / 10).");

			List<DATATYPE_BASE> pAvatar_onReqsSkillLstResult_args = new List<DATATYPE_BASE>();
			pAvatar_onReqsSkillLstResult_args.Add(EntityDef.id2datatypes[25]);

			Method pAvatar_onReqsSkillLstResult = new Method();
			pAvatar_onReqsSkillLstResult.name = "onReqsSkillLstResult";
			pAvatar_onReqsSkillLstResult.methodUtype = 11;
			pAvatar_onReqsSkillLstResult.aliasID = 9;
			pAvatar_onReqsSkillLstResult.args = pAvatar_onReqsSkillLstResult_args;

			pAvatarModule.methods["onReqsSkillLstResult"] = pAvatar_onReqsSkillLstResult; 
			pAvatarModule.useMethodDescrAlias = true;
			pAvatarModule.idmethods[(UInt16)pAvatar_onReqsSkillLstResult.aliasID] = pAvatar_onReqsSkillLstResult;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(onReqsSkillLstResult / 11).");

			List<DATATYPE_BASE> pAvatar_leaveGame_args = new List<DATATYPE_BASE>();

			Method pAvatar_leaveGame = new Method();
			pAvatar_leaveGame.name = "leaveGame";
			pAvatar_leaveGame.methodUtype = 6;
			pAvatar_leaveGame.aliasID = -1;
			pAvatar_leaveGame.args = pAvatar_leaveGame_args;

			pAvatarModule.methods["leaveGame"] = pAvatar_leaveGame; 
			pAvatarModule.base_methods["leaveGame"] = pAvatar_leaveGame;

			pAvatarModule.idbase_methods[pAvatar_leaveGame.methodUtype] = pAvatar_leaveGame;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(leaveGame / 6).");

			List<DATATYPE_BASE> pAvatar_reqExitMatch_args = new List<DATATYPE_BASE>();

			Method pAvatar_reqExitMatch = new Method();
			pAvatar_reqExitMatch.name = "reqExitMatch";
			pAvatar_reqExitMatch.methodUtype = 9;
			pAvatar_reqExitMatch.aliasID = -1;
			pAvatar_reqExitMatch.args = pAvatar_reqExitMatch_args;

			pAvatarModule.methods["reqExitMatch"] = pAvatar_reqExitMatch; 
			pAvatarModule.base_methods["reqExitMatch"] = pAvatar_reqExitMatch;

			pAvatarModule.idbase_methods[pAvatar_reqExitMatch.methodUtype] = pAvatar_reqExitMatch;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(reqExitMatch / 9).");

			List<DATATYPE_BASE> pAvatar_reqHeroInfosByHeroId_args = new List<DATATYPE_BASE>();
			pAvatar_reqHeroInfosByHeroId_args.Add(EntityDef.id2datatypes[8]);

			Method pAvatar_reqHeroInfosByHeroId = new Method();
			pAvatar_reqHeroInfosByHeroId.name = "reqHeroInfosByHeroId";
			pAvatar_reqHeroInfosByHeroId.methodUtype = 7;
			pAvatar_reqHeroInfosByHeroId.aliasID = -1;
			pAvatar_reqHeroInfosByHeroId.args = pAvatar_reqHeroInfosByHeroId_args;

			pAvatarModule.methods["reqHeroInfosByHeroId"] = pAvatar_reqHeroInfosByHeroId; 
			pAvatarModule.base_methods["reqHeroInfosByHeroId"] = pAvatar_reqHeroInfosByHeroId;

			pAvatarModule.idbase_methods[pAvatar_reqHeroInfosByHeroId.methodUtype] = pAvatar_reqHeroInfosByHeroId;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(reqHeroInfosByHeroId / 7).");

			List<DATATYPE_BASE> pAvatar_reqSkillLst_args = new List<DATATYPE_BASE>();

			Method pAvatar_reqSkillLst = new Method();
			pAvatar_reqSkillLst.name = "reqSkillLst";
			pAvatar_reqSkillLst.methodUtype = 8;
			pAvatar_reqSkillLst.aliasID = -1;
			pAvatar_reqSkillLst.args = pAvatar_reqSkillLst_args;

			pAvatarModule.methods["reqSkillLst"] = pAvatar_reqSkillLst; 
			pAvatarModule.base_methods["reqSkillLst"] = pAvatar_reqSkillLst;

			pAvatarModule.idbase_methods[pAvatar_reqSkillLst.methodUtype] = pAvatar_reqSkillLst;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(reqSkillLst / 8).");

			List<DATATYPE_BASE> pAvatar_startGame_args = new List<DATATYPE_BASE>();

			Method pAvatar_startGame = new Method();
			pAvatar_startGame.name = "startGame";
			pAvatar_startGame.methodUtype = 5;
			pAvatar_startGame.aliasID = -1;
			pAvatar_startGame.args = pAvatar_startGame_args;

			pAvatarModule.methods["startGame"] = pAvatar_startGame; 
			pAvatarModule.base_methods["startGame"] = pAvatar_startGame;

			pAvatarModule.idbase_methods[pAvatar_startGame.methodUtype] = pAvatar_startGame;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(startGame / 5).");

			List<DATATYPE_BASE> pAvatar_submitStatisticalResult_args = new List<DATATYPE_BASE>();
			pAvatar_submitStatisticalResult_args.Add(EntityDef.id2datatypes[8]);

			Method pAvatar_submitStatisticalResult = new Method();
			pAvatar_submitStatisticalResult.name = "submitStatisticalResult";
			pAvatar_submitStatisticalResult.methodUtype = 4;
			pAvatar_submitStatisticalResult.aliasID = -1;
			pAvatar_submitStatisticalResult.args = pAvatar_submitStatisticalResult_args;

			pAvatarModule.methods["submitStatisticalResult"] = pAvatar_submitStatisticalResult; 
			pAvatarModule.cell_methods["submitStatisticalResult"] = pAvatar_submitStatisticalResult;

			pAvatarModule.idcell_methods[pAvatar_submitStatisticalResult.methodUtype] = pAvatar_submitStatisticalResult;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(submitStatisticalResult / 4).");

			ScriptModule pFrameSyncReportModule = new ScriptModule("FrameSyncReport");
			EntityDef.moduledefs["FrameSyncReport"] = pFrameSyncReportModule;
			EntityDef.idmoduledefs[2] = pFrameSyncReportModule;

			Property pFrameSyncReport_position = new Property();
			pFrameSyncReport_position.name = "position";
			pFrameSyncReport_position.properUtype = 40000;
			pFrameSyncReport_position.properFlags = 4;
			pFrameSyncReport_position.aliasID = 1;
			Vector3 FrameSyncReport_position_defval = new Vector3();
			pFrameSyncReport_position.defaultVal = FrameSyncReport_position_defval;
			pFrameSyncReportModule.propertys["position"] = pFrameSyncReport_position; 

			pFrameSyncReportModule.usePropertyDescrAlias = true;
			pFrameSyncReportModule.idpropertys[(UInt16)pFrameSyncReport_position.aliasID] = pFrameSyncReport_position;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(FrameSyncReport), property(position / 40000).");

			Property pFrameSyncReport_direction = new Property();
			pFrameSyncReport_direction.name = "direction";
			pFrameSyncReport_direction.properUtype = 40001;
			pFrameSyncReport_direction.properFlags = 4;
			pFrameSyncReport_direction.aliasID = 2;
			Vector3 FrameSyncReport_direction_defval = new Vector3();
			pFrameSyncReport_direction.defaultVal = FrameSyncReport_direction_defval;
			pFrameSyncReportModule.propertys["direction"] = pFrameSyncReport_direction; 

			pFrameSyncReportModule.usePropertyDescrAlias = true;
			pFrameSyncReportModule.idpropertys[(UInt16)pFrameSyncReport_direction.aliasID] = pFrameSyncReport_direction;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(FrameSyncReport), property(direction / 40001).");

			Property pFrameSyncReport_spaceID = new Property();
			pFrameSyncReport_spaceID.name = "spaceID";
			pFrameSyncReport_spaceID.properUtype = 40002;
			pFrameSyncReport_spaceID.properFlags = 16;
			pFrameSyncReport_spaceID.aliasID = 3;
			UInt32 FrameSyncReport_spaceID_defval;
			UInt32.TryParse("", out FrameSyncReport_spaceID_defval);
			pFrameSyncReport_spaceID.defaultVal = FrameSyncReport_spaceID_defval;
			pFrameSyncReportModule.propertys["spaceID"] = pFrameSyncReport_spaceID; 

			pFrameSyncReportModule.usePropertyDescrAlias = true;
			pFrameSyncReportModule.idpropertys[(UInt16)pFrameSyncReport_spaceID.aliasID] = pFrameSyncReport_spaceID;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(FrameSyncReport), property(spaceID / 40002).");

			Property pFrameSyncReport_seatNo = new Property();
			pFrameSyncReport_seatNo.name = "seatNo";
			pFrameSyncReport_seatNo.properUtype = 19;
			pFrameSyncReport_seatNo.properFlags = 16;
			pFrameSyncReport_seatNo.aliasID = 4;
			SByte FrameSyncReport_seatNo_defval;
			SByte.TryParse("0", out FrameSyncReport_seatNo_defval);
			pFrameSyncReport_seatNo.defaultVal = FrameSyncReport_seatNo_defval;
			pFrameSyncReportModule.propertys["seatNo"] = pFrameSyncReport_seatNo; 

			pFrameSyncReportModule.usePropertyDescrAlias = true;
			pFrameSyncReportModule.idpropertys[(UInt16)pFrameSyncReport_seatNo.aliasID] = pFrameSyncReport_seatNo;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(FrameSyncReport), property(seatNo / 19).");

			List<DATATYPE_BASE> pFrameSyncReport_onFrameMessage_args = new List<DATATYPE_BASE>();
			pFrameSyncReport_onFrameMessage_args.Add(EntityDef.id2datatypes[38]);

			Method pFrameSyncReport_onFrameMessage = new Method();
			pFrameSyncReport_onFrameMessage.name = "onFrameMessage";
			pFrameSyncReport_onFrameMessage.methodUtype = 21;
			pFrameSyncReport_onFrameMessage.aliasID = 1;
			pFrameSyncReport_onFrameMessage.args = pFrameSyncReport_onFrameMessage_args;

			pFrameSyncReportModule.methods["onFrameMessage"] = pFrameSyncReport_onFrameMessage; 
			pFrameSyncReportModule.useMethodDescrAlias = true;
			pFrameSyncReportModule.idmethods[(UInt16)pFrameSyncReport_onFrameMessage.aliasID] = pFrameSyncReport_onFrameMessage;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(FrameSyncReport), method(onFrameMessage / 21).");

			List<DATATYPE_BASE> pFrameSyncReport_reportFrame_args = new List<DATATYPE_BASE>();
			pFrameSyncReport_reportFrame_args.Add(EntityDef.id2datatypes[37]);

			Method pFrameSyncReport_reportFrame = new Method();
			pFrameSyncReport_reportFrame.name = "reportFrame";
			pFrameSyncReport_reportFrame.methodUtype = 19;
			pFrameSyncReport_reportFrame.aliasID = -1;
			pFrameSyncReport_reportFrame.args = pFrameSyncReport_reportFrame_args;

			pFrameSyncReportModule.methods["reportFrame"] = pFrameSyncReport_reportFrame; 
			pFrameSyncReportModule.cell_methods["reportFrame"] = pFrameSyncReport_reportFrame;

			pFrameSyncReportModule.idcell_methods[pFrameSyncReport_reportFrame.methodUtype] = pFrameSyncReport_reportFrame;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(FrameSyncReport), method(reportFrame / 19).");

		}

		public static void initDefTypes()
		{
			{
				UInt16 utype = 2;
				string typeName = "CMD_TYPE";
				string name = "UINT8";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 3;
				string typeName = "UINT16";
				string name = "UINT16";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 5;
				string typeName = "SPACE_KEY";
				string name = "UINT64";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 4;
				string typeName = "MATCH_ID";
				string name = "UINT32";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 6;
				string typeName = "INT8";
				string name = "INT8";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 7;
				string typeName = "INT16";
				string name = "INT16";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 8;
				string typeName = "MATCHTIME";
				string name = "INT32";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 9;
				string typeName = "INT64";
				string name = "INT64";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 1;
				string typeName = "STRING";
				string name = "STRING";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 12;
				string typeName = "NAME";
				string name = "UNICODE";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 13;
				string typeName = "FLOAT";
				string name = "FLOAT";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 14;
				string typeName = "DOUBLE";
				string name = "DOUBLE";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 10;
				string typeName = "PYTHON";
				string name = "PYTHON";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 10;
				string typeName = "PY_DICT";
				string name = "PY_DICT";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 10;
				string typeName = "PY_TUPLE";
				string name = "PY_TUPLE";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 10;
				string typeName = "PY_LIST";
				string name = "PY_LIST";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 20;
				string typeName = "ENTITYCALL";
				string name = "ENTITYCALL";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 11;
				string typeName = "BLOB";
				string name = "BLOB";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 15;
				string typeName = "VECTOR2";
				string name = "VECTOR2";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 16;
				string typeName = "DIRECTION3D";
				string name = "VECTOR3";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 17;
				string typeName = "VECTOR4";
				string name = "VECTOR4";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 22;
				string typeName = "HERO_IDS_LIST";
				DATATYPE_HERO_IDS_LIST datatype = new DATATYPE_HERO_IDS_LIST();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 23;
				string typeName = "HERO_INFOS";
				DATATYPE_HERO_INFOS datatype = new DATATYPE_HERO_INFOS();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 24;
				string typeName = "SKILL_INFOS";
				DATATYPE_SKILL_INFOS datatype = new DATATYPE_SKILL_INFOS();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 25;
				string typeName = "SKILL_INFOS_LIST";
				DATATYPE_SKILL_INFOS_LIST datatype = new DATATYPE_SKILL_INFOS_LIST();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 26;
				string typeName = "SHOP_INFOS";
				DATATYPE_SHOP_INFOS datatype = new DATATYPE_SHOP_INFOS();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 27;
				string typeName = "SHOP_INFOS_LIST";
				DATATYPE_SHOP_INFOS_LIST datatype = new DATATYPE_SHOP_INFOS_LIST();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 28;
				string typeName = "PROPS_INFOS";
				DATATYPE_PROPS_INFOS datatype = new DATATYPE_PROPS_INFOS();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 29;
				string typeName = "PROPS_INFOS_LIST";
				DATATYPE_PROPS_INFOS_LIST datatype = new DATATYPE_PROPS_INFOS_LIST();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 30;
				string typeName = "AVATAR_INFOS";
				DATATYPE_AVATAR_INFOS datatype = new DATATYPE_AVATAR_INFOS();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 31;
				string typeName = "AVATAR_INFOS_LIST";
				DATATYPE_AVATAR_INFOS_LIST datatype = new DATATYPE_AVATAR_INFOS_LIST();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 33;
				string typeName = "MATCHING_INFOS";
				DATATYPE_MATCHING_INFOS datatype = new DATATYPE_MATCHING_INFOS();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 35;
				string typeName = "MATCHING_INFOS_LIST";
				DATATYPE_MATCHING_INFOS_LIST datatype = new DATATYPE_MATCHING_INFOS_LIST();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 37;
				string typeName = "FS_ENTITY_DATA";
				DATATYPE_FS_ENTITY_DATA datatype = new DATATYPE_FS_ENTITY_DATA();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 38;
				string typeName = "FS_FRAME_DATA";
				DATATYPE_FS_FRAME_DATA datatype = new DATATYPE_FS_FRAME_DATA();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 40;
				string typeName = "FS_FRAME_LIST";
				DATATYPE_FS_FRAME_LIST datatype = new DATATYPE_FS_FRAME_LIST();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 42;
				string typeName = "AnonymousArray_42";
				string name = "ENTITY_COMPONENT";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 43;
				string typeName = "AnonymousArray_43";
				string name = "ENTITY_COMPONENT";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 44;
				string typeName = "AnonymousArray_44";
				string name = "ENTITY_COMPONENT";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 45;
				string typeName = "AnonymousArray_45";
				string name = "ENTITY_COMPONENT";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 46;
				string typeName = "AnonymousArray_46";
				string name = "ENTITY_COMPONENT";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			foreach(string datatypeStr in EntityDef.datatypes.Keys)
			{
				DATATYPE_BASE dataType = EntityDef.datatypes[datatypeStr];
				if(dataType != null)
				{
					dataType.bind();
				}
			}
		}

	}


}